# About this notebook


In this notebook you see a simplified version of LoRA.


# Imports

In [ ]:
import numpy as np

In [ ]:
# Function to decompose a matrix W into low-rank matrices A and B
def lora_decomposition(W, r):
    # Initialize B with zeros (d x r) and A with random Gaussian values (r x d)
    B = np.zeros((W.shape[0], r))
    A = np.random.normal(0, 1, (r, W.shape[1]))

    # For an illustrative example, we compute A and B using SVD for the optimal low-rank approximation
    U, S, Vt = np.linalg.svd(W, full_matrices=False)
    B[:, :r] = U[:, :r] * np.sqrt(S[:r])
    A[:r, :] = np.sqrt(S[:r])[:, np.newaxis] * Vt[:r, :]

    # Compute the low-rank approximation of W
    W_approx = B @ A

    return B, A, W_approx

# Create a random integer square matrix W with dimension d x d
d = 6  # Dimension of the square matrix
W = np.random.randint(0, 10, size=(d, d))

# Choose a rank r for the low-rank approximation, with r < d
r = 5  # Rank for the decomposition

# Perform the decomposition
B, A, W_approx = lora_decomposition(W, r)

# Output the matrices and the approximation
print("Original matrix W:")
print(W)
print("\nMatrix B (after decomposition):")
print(B)
print("\nMatrix A (after decomposition):")
print(A)
print("\nLow-rank approximation of W (W_approx):")
print(W_approx)
print("\nLow-rank approximation of W (W_approx) converted to integer:")
print(W_approx.round(0).astype(int))



Original matrix W:
[[2 8 2 4 5 1]
 [7 4 6 7 1 5]
 [7 1 8 7 0 3]
 [5 1 0 0 0 5]
 [5 3 1 0 5 7]
 [7 5 3 2 1 2]]

Matrix B (after decomposition):
[[-1.63975843 -1.33957697 -2.07707937 -0.16573653  0.18276492]
 [-2.69725086  0.70080261 -0.06759739 -0.29920634  0.81155888]
 [-2.43915942  1.84683617  0.07585973 -0.41680288 -0.57780471]
 [-1.08102782 -0.56800259  1.53387208  0.50825529  0.6897052 ]
 [-1.67257669 -1.79246668  1.13205129 -0.86851545 -0.54666945]
 [-1.85552222 -0.31598708 -0.07997718  1.61607965 -0.49072672]]

Matrix A (after decomposition):
[[-2.82949436 -1.78893697 -1.98157622 -1.98198396 -0.90532274 -1.85518664]
 [ 0.12216945 -1.4565141   1.45308667  1.26912081 -1.63691814 -0.89096464]
 [ 1.08890724 -1.54181904 -0.38426074 -1.0558866  -0.61174412  1.66300157]
 [ 1.06453149  0.77740217 -0.37838641 -0.62396052 -0.98449913 -0.82204055]
 [-0.35179518  0.35596623 -0.68899414  0.67894206 -0.734205    0.56217305]]

Low-rank approximation of W (W_approx):
[[ 1.97355752  8.02323197  2